# Urubu build system
#
# Copyright (c) 2013 Zoltan Kovacs
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Import("env")

client_sources = [
    "device.c",
    "async.c"
]

server_sources = [
    "device.c"
]

# add the include directory of the library to the global environment
env["CPPPATH"] += [Dir("include")]

# Build the devman libraries
libdevman_client = env.StaticLibrary(target = "devman_client", source = ["src/client/%s" % x for x in client_sources])
libdevman_server = env.StaticLibrary(target = "devman_server", source = ["src/server/%s" % x for x in server_sources])

# Install to the library path of GCC
libdevman_client_install = Command(
    "#toolchain/%s/lib/gcc/%s-pc-urubu/%s/libdevman_client.a" % (env["ARCH"], "x86_64", "4.7.3"),
    str(libdevman_client[0]),
    Action("cp $SOURCE $TARGET", env["CPCOMSTR"]))
Depends(libdevman_client_install, libdevman_client)

libdevman_server_install = Command(
    "#toolchain/%s/lib/gcc/%s-pc-urubu/%s/libdevman_server.a" % (env["ARCH"], "x86_64", "4.7.3"),
    str(libdevman_server[0]),
    Action("cp $SOURCE $TARGET", env["CPCOMSTR"]))
Depends(libdevman_server_install, libdevman_server)

env["LIBRARIES"] += [libdevman_client_install, libdevman_server_install]
