# Urubu build system
#
# Copyright (c) 2013 Zoltan Kovacs
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Import("env")

crt0 = env.Object("src/%s/crt0.S" % env["ARCH"])

crt0_install = Command(
    "#toolchain/%s/lib/gcc/%s-pc-urubu/%s/crt0.o" % (env["ARCH"], "x86_64", "4.7.3"),
    str(crt0[0]),
    Action("cp $SOURCE $TARGET", env["CPCOMSTR"]))
Depends(crt0_install, crt0)

env["LIBRARIES"].append(crt0_install)
