# Urubu build system
#
# Copyright (c) 2013 Zoltan Kovacs
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Import("kenv")

kenv["CFLAGS"] += ["-mcmodel=kernel"]
kenv["LINKERSCRIPT"] = File("link.ld")

sources = [
    "asm/start.S",
    "asm/gdt.S",
    "asm/isr.S",
    "asm/cpu.S",
    "asm/sched.S",
    "cpu/gdt.c",
    "cpu/idt.c",
    "cpu/irq.c",
    "cpu/atomic.c",
    "cpu/cpu.c",
    "mm/vmm.c",
    "mm/pmm.c",
    "proc/process.c",
    "proc/thread.c",
    "proc/sched.c",
    "start.c",
    "exception.c",
    "syscall.c"
]

Return("sources")
