# Urubu build system
#
# Copyright (c) 2013 Zoltan Kovacs
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Import("env")

sources = ["slab.c", "hashtable.c"]

# add the include directory of the library to the global environment
env["CPPPATH"] += [Dir("include")]

# Build the C library
libsupport = env.StaticLibrary(target = "support", source = ["src/%s" % x for x in sources])

# Install to the library path of GCC
libsupport_install = Command(
    "#toolchain/%s/lib/gcc/%s-pc-urubu/%s/libsupport.a" % (env["ARCH"], "x86_64", "4.7.3"),
    str(libsupport[0]),
    Action("cp $SOURCE $TARGET", env["CPCOMSTR"]))
Depends(libsupport_install, libsupport)

env["LIBRARIES"].append(libsupport_install)
